client/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('bookings/', ClientsListView.as_view(), name='clients'),
    path('clients/', OnlyClientsRead.as_view(), name='clients_only'),
    # path('barber/clients/<int:barber_id>/', BarberClientsListView.as_view(), name='barber-clients'),
    path('new-site/', booking_view, name='create'),
    path('get-barber-data/', get_data_for_barber, name='get_barber_data'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='delete'),
    path('clients/complete/<int:client_id>/', complete_client, name='complete_client'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('client.urls')),
    path('', include('pages.urls')),
    path('registration/', include('accounts.urls')),
    path('registration/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from client.views import *
from .views import *

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin_view, name='admin'),
    path('profile/', profile_view, name='profile_view'),
    path('profile/edit/', profile_edit, name='profile_edit'),
    path('profile/site/update/', site_update, name='site_update'),
    path('profile/barber/barbers/', BarberCreateView.as_view(), name='add_barber'),
    path('profile/sites/<int:pk>/delete/', DeleteBarbers.as_view(), name='delete_barber'),
    path('not_barber/', not_barber, name='not_barber'),
    path('profile/manage-schedule/', manage_schedule_view, name='manage_schedule'),
    path('profile/users/', users_list, name='users_list'),
    path('profile/make-admin/<int:user_id>/', make_admin, name='make_admin'),
    path('profile/remove-admin/<int:user_id>/', remove_admin, name='remove_admin'),
    path('profile/users/delete/<int:user_id>/', delete_user, name='remove_user'),
    path('profile/levels/', LevelManageView.as_view(), name='level_list'),
    path('profile/levels/delete/<int:pk>/', LevelDeleteView.as_view(), name='delete_level'),

    path('ajax/levels/', get_levels_by_barber, name='ajax_levels'),
    path('ajax/dates/', get_dates_by_barber, name='ajax_dates'),
    path('ajax/times/', get_times_by_barber, name='ajax_times'),
    path('profile/balance/', account_view, name='balance'),
    path('profile/reset_balance/<int:user_id>/', reset_account_balance, name='reset_balance'),
    path('profile/staff-codes/', staff_codes_page, name='staffcode-page'),

]

client/models.py
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.urls import reverse
from accounts.models import BarberUser
from config import settings


#Barber uchun model<<<
User = get_user_model()
class Barber(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, limit_choices_to={'is_staff': True})
    tajriba = models.IntegerField( null=True, blank=True)
    haqida = models.CharField(max_length=100, null=True, blank=True)
    yoshi = models.IntegerField( null=True, blank=True)
    rasmi = models.ImageField(upload_to='barber_image/', null=True, blank=True)

    def __str__(self):
        return str(self.user)

#Tarif uchun modeli<<<
class Level(models.Model):
    barber = models.ForeignKey(
        Barber, on_delete=models.CASCADE, related_name='levels'
    )
    name = models.CharField(max_length=50)
    value = models.DecimalField(max_digits=15, decimal_places=3)

    class Meta:
        unique_together = ('barber', 'name')

    def __str__(self):
        return f"{self.name} ({self.barber})"

#Sana uchun model<<<
class Date(models.Model):
    barber = models.ForeignKey(Barber, on_delete=models.CASCADE)
    date = models.DateField()

    class Meta:
        unique_together = ('barber', 'date')

    def __str__(self):
        return f"{self.barber} | {self.date.strftime('%d.%m.%Y')}"

#Vaqt uchun model<<<
class Time(models.Model):
    barber = models.ForeignKey(Barber, on_delete=models.CASCADE)
    date = models.ForeignKey(Date, on_delete=models.CASCADE, related_name='times', null=True)
    time = models.TimeField()

    class Meta:
        unique_together = ('barber', 'time')

    def __str__(self):
        return f" {self.barber} | {self.time.strftime('%H:%M')}"

#Mijoz uchun model<<<
class Client(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    ism = models.CharField(max_length=100, null=True)
    familiya = models.CharField(max_length=100, null=True, blank=True, default='')
    telefon = models.CharField(max_length=100, null=True)
    barber = models.ForeignKey(Barber, on_delete=models.CASCADE, null=True, related_name='clients')
    sana = models.ForeignKey(Date, on_delete=models.CASCADE, null=True)
    vaqt = models.ForeignKey(Time, on_delete=models.CASCADE, null=True)
    level = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=True)

    def calculate_amount(self):
        return self.level.value if self.level else Decimal('0.000')

    def __str__(self):
        return f"{self.ism} "

    def get_absolute_url(self):
        return reverse('home', kwargs={'pk': self.pk})

#Balans uchun model<<<
class Balance(models.Model):
    user = models.ForeignKey(BarberUser, on_delete=models.CASCADE, related_name='withdrawals')
    amount = models.DecimalField(max_digits=20, decimal_places=3)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.amount} so'm - {self.date.strftime('%Y-%m-%d %H:%M')}"

#Admin Code uchun model<<<
class StaffCode(models.Model):
    code = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.code

client/views.py
import logging
import threading
import datetime
from datetime import datetime, timedelta
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Sum
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, View, CreateView
from django.views.generic.edit import DeleteView
from sms.sms import send_sms
from .forms import ClientForm, LevelForm, BalanceForm, DateForm, TimeForm
from .models import Client, Level, Date, Time, Balance, StaffCode, Barber

class BarberRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        try:
            self.barber = Barber.objects.get(user=request.user)
        except Barber.DoesNotExist:
            return redirect('not_barber')
        return super().dispatch(request, *args, **kwargs)

# Bandlik yaratish<<<
@login_required
def booking_view(request):
    barbers = Barber.objects.all()
    selected_barber_id = request.GET.get('barber_id') or request.POST.get('barber')

    days = Date.objects.none()
    times = Time.objects.none()
    levels = Level.objects.none()
    if selected_barber_id:
        try:
            barber = Barber.objects.get(id=selected_barber_id)
            user_id = barber.id
            days = Date.objects.filter(barber_id=user_id)
            times = Time.objects.filter(barber_id=user_id)
            levels = Level.objects.filter(barber_id=user_id)
        except Barber.DoesNotExist:
            pass

    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            barber = Barber.objects.get(id=request.POST.get('barber'))
            booking = form.save(commit=False, barber_user=barber.user)  # owner sifatida barber.user
            booking.barber = barber
            booking.owner = request.user
            booking.save()
            # yaratiliganda
            phone = str(booking.telefon)
            phone = phone.replace(" ", "")
            phone = phone.replace("-", "")
            name = booking.ism
            tm = f"{booking.sana.date.strftime('%B %d, %Y')} sanasi, {booking.vaqt.time.strftime('%H:%M')}"
            text = f"Salom {name}\nSiz BarberShopdan joy band qildingiz.\nNavbatingiz:{tm} da.\nRaxmat )"
            print(text)
            send_sms(phone, text)

            # rejalashtirish 2soat oldn
            date_obj = booking.sana.date
            time_obj = booking.vaqt.time
            booking_datetime = datetime.combine(date_obj, time_obj)
            reminder_datetime = booking_datetime - timedelta(hours=2)
            print("Band qilingan vaqt:", booking_datetime)
            print("SMS yuboriladigan vaqt:", reminder_datetime)

            def schedule_sms(phone, text, send_time):
                delay = (send_time - datetime.now()).total_seconds()
                if delay > 0:
                    threading.Timer(delay, send_sms, args=[phone, text]).start()
                else:
                    print("SMS yuborish vaqti o‘tib ketgan.")

            sms_text = f"Hurmatli mijoz!\n{tm}ga band qilgan joyingizni unutmang!\nNavbatingiz kelishiga atiga 2soat qoldi."
            schedule_sms(phone, sms_text, reminder_datetime)

            return redirect('home')

    else:
        form = ClientForm()

    context = {
        'barbers': barbers,
        'days': days,
        'times': times,
        'levels': levels,
        'form': form,
        'selected_barber_id': selected_barber_id,
    }

    return render(request, 'bookings/new_booking.html', context)

def client_add_done(request):
    booking = Client.objects.first()
    return  render(request, "bookings/new_booking_done.html", {"booking": booking})

# Band qilingan joylar listi<<<
class ClientsListView(ListView, LoginRequiredMixin):
    model = Client
    template_name = 'bookings/bookings.html'
    context_object_name = 'clients'

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            return Client.objects.all().order_by('sana', 'vaqt')

        elif hasattr(user, 'barber'):
            return Client.objects.filter(barber=user.barber).order_by('sana', 'vaqt')
        else:
            return Client.objects.filter(owner=user).order_by('sana', 'vaqt')



class OnlyClientsRead(ListView, LoginRequiredMixin):
    model = Client
    template_name = 'bookings/bookings_view.html'
    context_object_name = 'clients_only'

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            return Client.objects.all().order_by('sana', 'vaqt')

        elif hasattr(user, 'barber'):
            return Client.objects.filter(barber=user.barber).order_by('sana', 'vaqt')

        else:
            return Client.objects.filter(owner=user).order_by('sana', 'vaqt')



# Band qilingan joylarni o'chirish<<<
class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Client
    template_name = 'bookings/delete_booking.html'
    success_url = reverse_lazy('clients')

    def test_func(self):
        obj = self.get_object()
        admin = self.request.user.is_superuser or self.request.user.is_staff
        owner = obj.owner == self.request.user
        return admin or owner

    def get(self, request, *args, **kwargs):
        """ GET so‘rovni bloklab, faqat POST orqali o‘chirishga ruxsat beramiz """
        return self.post(request, *args, **kwargs)




# Band qilingan joyni tugatish va balans qo'shish<<<
logger = logging.getLogger(__name__)
def complete_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    if request.method == 'POST':
        logger.debug(f"Client: {client}, Owner: {client.owner}, Level: {client.level}")
        client.status = 'completed'
        client.save()
        if client.owner:
            amount = client.calculate_amount()
            if amount is None:
                return JsonResponse({'status': 'error', 'message': 'Hisoblangan qiymat noto‘g‘ri.'})
            client.owner.account_balance += amount
            client.owner.save()
        client.delete()
        return redirect('clients')

    return JsonResponse({'status': 'error', 'message': 'Invalid request.'})

#Barber yaratish va boshqarish<<<
class BarberCreateView(CreateView):
    model = Barber
    fields = '__all__'
    template_name = 'barbers/add_barber.html'
    success_url = reverse_lazy('add_barber')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        staff_users = User.objects.filter(is_staff=True)
        barber_users = Barber.objects.values_list('user_id', flat=True)
        available_users = staff_users.exclude(id__in=barber_users)

        context['users'] = available_users
        context['barbers'] = Barber.objects.all()
        return context

#No barber
def not_barber(request):
    return render(request, 'barbers/not_barber.html')

#Barberni o'chirish<<<
class DeleteBarbers(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Barber
    success_url = reverse_lazy('add_barber')
    template_name = 'barbers/delete_barber.html'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def delete(self, request, *args, **kwargs):
        barber = self.get_object()
        user = barber.user
        if user.id != request.user.id:
            Level.objects.filter(barber=user).delete()
            Date.objects.filter(barber=user).delete()
            Time.objects.filter(barber=user).delete()

            if request.user != user:
                user.is_staff = False
                user.is_superuser = False
                user.save()
            super().delete(request, *args, **kwargs)

        return redirect(self.success_url)


# Sana va Vaqt malumotlarini olish<<<
def get_data_for_barber(request):
    barber_id = request.GET.get('barber_id')
    response = {}

    if barber_id:
        date_objs = Date.objects.filter(barber_id=barber_id)
        dates = [{'id': obj.id, 'date': obj.date.strftime('%Y-%m-%d')} for obj in date_objs]
        response['dates'] = dates

        time_objs = Time.objects.filter(barber_id=barber_id)
        times = [{'id': obj.id, 'time': obj.time.strftime('%H:%M')} for obj in time_objs]
        response['times'] = times

    return JsonResponse(response)




# Tarif yaratish va boshqarish<<<
class LevelManageView(LoginRequiredMixin, View):
    template_name = 'pages/levels_list.html'

    def get(self, request):
        form = LevelForm()
        if request.user.is_superuser:
            levels = Level.objects.all()
        else:
            try:
                barber = Barber.objects.get(user=request.user)
            except Barber.DoesNotExist:
                return redirect('not_barber')
            levels = Level.objects.filter(barber=barber)
        return render(request, self.template_name, {'form': form, 'levels': levels})

    def post(self, request):
        form = LevelForm(request.POST)
        if form.is_valid():
            level = form.save(commit=False)
            level.barber = Barber.objects.get(user=request.user)
            level.save()
            return redirect('level_list')

        if request.user.is_superuser:
            levels = Level.objects.all()
        else:
            levels = Level.objects.filter(barber=request.user)

        return render(request, self.template_name, {'form': form, 'levels': levels})


# Tarifni o'chirish<<<
class LevelDeleteView(LoginRequiredMixin, DeleteView):
    model = Level
    template_name = 'pages/levels_list.html'
    success_url = reverse_lazy('level_list')

    def test_func(self):

templates/bookings/bookings.html
{% extends 'pages/profile.html' %}
{% load static %}
{% block title %}Profile | Mijozlar{% endblock title %}
{% block css %}{% static 'css/bookings/clients.css' %}{% endblock css %}
{% block main %}
    <div class="body" style="display: flex; flex-direction: column; gap: 30px;">
        {% if clients %}
          <div class="table">
            <table class="black">
                <tr>
                    <th>#</th>
                    <th>Ism</th>
                    <th>Telefon</th>
                    <th>ID</th>
                    <th>Tarif</th>
                    <th>Barber</th>
                    <th>Sana va Vaqt</th>
                    {% if request.user.is_superuser or request.user.is_staff %}
                        <th>Tugatish</th>
                        <th>O'chirish</th>
                    {% else %}
                        <th>Bekor qilish</th>
                    {% endif %}
                </tr>
                {% if request.user.is_superuser or request.user.is_staff %}
                    <h2 class="heading">Mijozlar ro‘yxati:</h2>
                {% else %}
                    <h2 class="heading">Mening navbatlarim:</h2>
                {% endif %}
                {% for post in clients %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        {% if post.familiya == None %}
                            <td>{{ post.ism }}</td>
                        {% else %}
                            <td>{{ post.ism }} {{ post.familiya }}</td>
                        {% endif %}
                        <td>{{ post.telefon }}</td>
                        <td>{{ post.id }}</td>
                        <td>{% if post.level %}{{ post.level.name }}{% else %}Tanlanmagan!{% endif %}</td>
                        <td>{{ post.barber }}</td>
                        <td>{{ post.sana.date }}, {{ post.vaqt.time }}</td>
                        {% if request.user.is_superuser or request.user.is_staff %}
                            {% if request.user == post.barber.user %}
                                <td>
                                    <form method="post" action="{% url 'complete_client' post.id %}">
                                        {% csrf_token %}
                                        <button onclick="return confirm('Mijozni tugatdingizmi?')" type="submit"
                                                class="btn  white">Tugatish
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <a class="btn bad-bg istisno" href="{% url 'delete' post.pk %}">O'chirish</a>
                                </td>
                            {% else %}
                                <td>Ruxsat yo'q</td>
                                <td>Ruxsat yo'q</td>
                            {% endif %}

                        {% else %}
                            <td>
                                <a class="btn bad-bg istisno" href="{% url 'delete' post.pk %}">Bekor qilish</a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}

            </table>
          </div>
            <a style="width: 100%;" href="{% url 'create' %} "><h1 class="black btn curve-border">+</h1></a>
        {% else %}

            <div class="container">
                {% if request.user.is_superuser or request.user.is_staff %}
                    <h2 class="heading">Hozircha mijozlar mavjud emas!</h2>
                {% else %}
                    <h2 class="heading">Hozircha bandlik mavjud emas!</h2>
                {% endif %}
                <a href="{% url 'create' %} "><h1 style="width: 20%; margin: auto;" class="btn black curve-border">
                    +</h1></a>
            </div>
        {% endif %}
    </div>


    <script>
        function showAlert(clientId) {
            document.getElementById('alert-popup').style.display = 'block';
            document.getElementById('complete-btn').setAttribute('data-client-id', clientId);
        }

        function closeAlert() {
            document.getElementById('alert-popup').style.display = 'none';
        }

    </script>
{% endblock main %}

templates/bookings/bookings_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Mijozlar{% endblock title %}
{% block css %}{% static 'css/bookings/clients.css' %}{% endblock css %}
{% block content %}
    <br>
    <br>
    <br>
    <br>
    <div class="body" style="display: flex; flex-direction: column; gap: 30px;">
        {% if clients_only %}
            <table class="table black">
                <tr>
                    <th>#</th>
                    <th>Ism</th>
                    <th>Telefon</th>
                    <th>ID</th>
                    <th>Tarif</th>
                    <th>Sana va Vaqt</th>
                    {% if request.user.is_superuser or request.user.is_staff %}
                        <th>Tugatish</th>
                        <th>O'chirish</th>
                    {% else %}
                        <th>Bekor qilish</th>
                    {% endif %}
                </tr>

                <h2 class="heading">Mijozlar ro‘yxati:</h2>

                {% for post in clients_only %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        {% if post.familiya == None %}
                            <td>{{ post.ism }}</td>
                        {% else %}
                            <td>{{ post.ism }} {{ post.familiya }}</td>
                        {% endif %}
                        <td>{{ post.telefon }}</td>
                        <td>{{ post.id }}</td>
                        <td>{% if post.level %}{{ post.level.name }}{% else %}Tanlanmagan!{% endif %}</td>
                        <td>{{ post.sana.date }}, {{ post.vaqt.time }}</td>
                        {% if request.user.is_superuser or request.user.is_staff %}
                            {% if request.user == post.owner %}
                                <td>
                                    <form method="post" action="{% url 'complete_client' post.id %}">
                                        {% csrf_token %}
                                        <button onclick="return confirm('Mijozni tugatdingizmi?')" type="submit"
                                                class="btn  white">Tugatish
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <a class="btn bad-bg istisno" href="{% url 'delete' post.pk %}">O'chirish</a>
                                </td>
                            {% else %}
                                <td>Ruxsat yo'q</td>
                                <td>Ruxsat yo'q</td>
                            {% endif %}
                        {% else %}
                            <td>
                                <a class="btn bad-bg istisno" href="{% url 'delete' post.pk %}">Bekor qilish</a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}

            </table>

        {% else %}

            <div class="container">
                {% if request.user.is_superuser or request.user.is_staff %}
                    <h2 class="heading">Hozircha mijozlar mavjud emas!</h2>
                {% else %}
                    <h2 class="heading">Hozircha bandlik mavjud emas!</h2>
                {% endif %}

            </div>
        {% endif %}
    </div>


    <script>
        function showAlert(clientId) {
            document.getElementById('alert-popup').style.display = 'block';
            document.getElementById('complete-btn').setAttribute('data-client-id', clientId);
        }

        function closeAlert() {
            document.getElementById('alert-popup').style.display = 'none';
        }

    </script>
{% endblock %}

templates/bookings/clients.html
{% extends 'pages/profile.html' %}
{% load static %}
{% block title%}Profil | Mijozlar{% endblock title %}
{% block css %}{% static 'css/bookings/clients.css' %}{% endblock css %}
{% block main %}
<div class="body">
    {% if clients %}
    <div class="table">
        <table class="black">
            <tr>
                <th>#</th>
                <th>Ism</th>
                <th>Telefon</th>
                <th>ID</th>
                <th>Tarif</th>
                <th>Sana va Vaqt</th>
                {% if request.user.is_superuser or request.user.is_staff %}
                <th>Tugatish</th>
                <th>O'chirish</th>
                {% else %}
                <th>Bekor qilish</th>
                {% endif %}
            </tr>
            {% if request.user.is_superuser or request.user.is_staff %}
            <h2 class="heading">Mijozlari ro‘yxati:</h2>
            {% else %}
            <h2 class="heading">Mening navbatlarim:</h2>
            {% endif %}
            {% for post in clients %}
            <tr>
                <td>{{ forloop.counter }}</td>
                {% if post.familiya == None %}
                <td>{{ post.ism }}</td>
                {% else %}
                <td>{{ post.ism }} {{ post.familiya }}</td>
                {% endif %}
                <td>{{ post.telefon }}</td>
                <td>{{ post.id }}</td>
                <td>{% if post.level %}{{ post.level.name }}{% else %}Tanlanmagan!{% endif %}</td>
                <td>{{ post.sana.date }}, {{ post.vaqt.time }}</td>
                {% if request.user.is_superuser or request.user.is_staff %}
                {% if request.user == post.owner %}
                <td>
                    <form method="post" action="{% url 'complete_client' post.id %}">
                        {% csrf_token %}
                        <button onclick="return confirm('Mijozni tugatdingizmi?')" type="submit"
                                class="btn  white">Tugatish
                        </button>
                    </form>
                </td>
                <td>
                    <a class="btn bad-bg istisno" href="{% url 'delete' post.pk %}">O'chirish</a>
                </td>
                {% else %}
                <td>Ruxsat yo'q</td>
                <td>Ruxsat yo'q</td>
                {% endif %}
                {% else %}
                <td>
                    <a class="btn bad-bg istisno" href="{% url 'delete' post.pk %}">Bekor qilish</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
    
        </table>
    </div>

    <a style="width: 100%;" href="{% url 'create' %} "><h1 class="black btn curve-border">Joy band qilish</h1></a>
    {% else %}
        
    <div class="container">
        {% if request.user.is_superuser or request.user.is_staff %}
        <h2 class="heading">Hozircha mijozlar mavjud emas!</h2>
        {% else %}
        <h2 class="heading">Hozircha bandlik mavjud emas!</h2>
        {% endif %}
        <a href="{% url 'create' %} "><h1 style="width: 100%; height: 30px;" class="btn light- black curve-border">+</h1></a>
    </div>
    {% endif %}
</div>


<script>
    function showAlert(clientId) {
        document.getElementById('alert-popup').style.display = 'block';
        document.getElementById('complete-btn').setAttribute('data-client-id', clientId);
    }

    function closeAlert() {
        document.getElementById('alert-popup').style.display = 'none';
    }

</script>
{% endblock main %}

templates/bookings/new_chosen.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Joy band qilish {% endblock title %}
{% block css %}{% static 'css/bookings/new_chosen.css' %}{% endblock css %}
{% block content %}

<div class="body1">
    <h2>Salondan joy band qilish</h2>
    <h6>
        Agar tushunmayotgan bo‘lsangiz, <a href="">yo‘riqnoma</a> bilan
        tanishing!
    </h6>
    <form method="post" id="booking_form">
        {% csrf_token %}
        <div>
            <label for="name">Ism</label>
            <input
                name="ism"
                type="text"
                id="name"
                placeholder="ism"
                required />
        </div>
        <div>
            <label for="familiya">Familiya</label>
            <input
                name="familiya"
                type="text"
                id="familiya"
                placeholder="familiya" />
        </div>
        <div>
            <label for="telefon">Telefon</label>
            <input
                name="telefon"
                type="tel"
                id="telefon"
                placeholder="telefon raqami"
                pattern="\+998\s[0-9]{2}\s[0-9]{3}\s[0-9]{2}-[0-9]{2}"
                required />
        </div>
        <div>
            <label for="id_sana">Sana</label>
            <select name="sana" id="id_sana" class="form-select" required>
                {% for value, label in form.fields.sana.widget.choices %}
                <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
            {{ form.sana.errors }}
        </div>

        <div>
            <label for="id_time">Vaqt</label>
            <select name="vaqt" id="id_time" class="form-select" required>
                {% for value, label in form.fields.vaqt.widget.choices %}
                <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
            {{ form.vaqt.errors }}
        </div>
        {% if form.non_field_errors %}
        <div style="width: 300px; height: 30px">
            {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <fieldset>
            <legend>Level:</legend>
            <label for="level_silver">
                <input type="radio" id="level_silver" name="level"
                value="silver" {% if form.level.value == 'silver' %} checked {%
                endif %}> Silver
            </label>
            <label for="level_gold">
                <input type="radio" id="level_gold" name="level" value="gold" {%
                if form.level.value == 'gold' %} checked {% endif %}> Gold
            </label>
            <label for="level_platinum">
                <input type="radio" id="level_platinum" name="level"
                value="platinum" {% if form.level.value == 'platinum' %} checked
                {% endif %}> Platinum
            </label>
        </fieldset>
        <button class="submit_btn" type="submit">Saqlash</button>
    </form>
</div>

<div id="confirmModal" class="modal">
    <div class="modal-content" style="width: 600px">
        <h5>Tasdiqlash</h5>
        <p>Haqiqatdan ham ushbu joyni band qilmoqchimisiz?</p>
        <div>
            <button id="confirmSubmit">Tasdiqlash</button>
            <button id="editConfirm">O'zgartirish</button>
            <form class="form" action="/">
                <button>Bekor qilish</button>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'js/new.js' %}"></script>
{% endblock content %}