config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('client.urls')),
    path('', include('pages.urls')),
    path('registration/', include('accounts.urls')),
    path('registration/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from client.views import *
from .views import *

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin_view, name='admin'),
    path('profile/', profile_view, name='profile_view'),
    path('profile/edit/', profile_edit, name='profile_edit'),
    path('profile/site/update/', site_update, name='site_update'),
    path('profile/barber/barbers/', BarberCreateView.as_view(), name='add_barber'),
    path('profile/sites/<int:pk>/delete/', DeleteBarbers.as_view(), name='delete_barber'),
    path('not_barber/', not_barber, name='not_barber'),
    path('profile/manage-schedule/', manage_schedule_view, name='manage_schedule'),
    path('profile/users/', users_list, name='users_list'),
    path('profile/make-admin/<int:user_id>/', make_admin, name='make_admin'),
    path('profile/remove-admin/<int:user_id>/', remove_admin, name='remove_admin'),
    path('profile/users/delete/<int:user_id>/', delete_user, name='remove_user'),
    path('profile/levels/', LevelManageView.as_view(), name='level_list'),
    path('profile/levels/delete/<int:pk>/', LevelDeleteView.as_view(), name='delete_level'),

    path('ajax/levels/', get_levels_by_barber, name='ajax_levels'),
    path('ajax/dates/', get_dates_by_barber, name='ajax_dates'),
    path('ajax/times/', get_times_by_barber, name='ajax_times'),
    path('profile/balance/', account_view, name='balance'),
    path('profile/reset_balance/<int:user_id>/', reset_account_balance, name='reset_balance'),
    path('profile/staff-codes/', staff_codes_page, name='staffcode-page'),

]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from client.models import StaffCode
from .models import BarberUser
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm


class BarberRegisterForm(UserCreationForm):
    is_staff_code_used = forms.BooleanField(required=False, label="Staffmanmisiz?")
    staff_code = forms.CharField(required=False, label="Staff kodi")

    class Meta:
        model = BarberUser
        fields = ('phone', 'first_name', 'last_name', 'profile_image')

    def clean(self):
        cleaned_data = super().clean()
        code_checked = cleaned_data.get('is_staff_code_used')
        code_input = cleaned_data.get('staff_code')

        if code_checked and code_input:
            if not StaffCode.objects.filter(code=code_input).exists():
                raise forms.ValidationError("Staff kodi noto‘g‘ri.")
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'Parol'
        self.fields['password2'].label = 'Parolni tasdiqlang'
        self.fields['first_name'].required = True
        self.fields['last_name'].required = False
        self.fields['profile_image'].required = False
        self.fields['staff_code'].required = False


class BarberLoginForm(AuthenticationForm):
    username = forms.CharField(label="Telefon raqam",
                               widget=forms.TextInput(attrs={'placeholder': 'Telefon raqamingiz'}))
    password = forms.CharField(label="Parol", widget=forms.PasswordInput(attrs={'placeholder': 'Parolingiz'}))
    error_messages = {
        'invalid_login': _("Telefon raqami yoki parol noto‘g‘ri. Iltimos, qaytadan urinib ko‘ring."),
        'inactive': _("Bu foydalanuvchi akkaunti o‘chirilgan."),
    }



class BarberPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Eski parol",
                                   widget=forms.PasswordInput(attrs={'placeholder': 'Eski parolingiz'}))
    new_password1 = forms.CharField(label="Yangi parol",
                                    widget=forms.PasswordInput(attrs={'placeholder': 'Yangi parol'}))
    new_password2 = forms.CharField(label="Yangi parolni tasdiqlang",
                                    widget=forms.PasswordInput(attrs={'placeholder': 'Yangi parolni tasdiqlang'}))


class BarberPasswordResetForm(forms.Form):
    phone = forms.CharField(
        label="Telefon raqam",
        error_messages={"invalid": "Telefon raqamni to‘g‘ri kiriting (masalan: +998901234567)"},
        widget=forms.TextInput(attrs={
            'placeholder': '+998901234567',
            'type': 'tel'
        })
    )


class BarberSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label="Yangi parol",
                                    widget=forms.PasswordInput(attrs={'placeholder': 'Yangi parol'}))
    new_password2 = forms.CharField(label="Yangi parolni tasdiqlang",
                                    widget=forms.PasswordInput(attrs={'placeholder': 'Yangi parolni tasdiqlang'}))

templates/default_auth/change_password.html
{% extends 'pages/profile.html' %}
{% load static %}
{% block title %}Parolni o‘zgartirish{% endblock %}
{% block css %}{% static 'css/accounts/change_password.css' %}{% endblock %}

{% block main %}
      <div class="body">
          <h1 class="black heading">Parolni o'zgartirish</h1>
      <form action="{% url 'login' %}" method="post" class="form inset-shadow curve-border">
          {% csrf_token %}
        <div class="gr">
            <label class="black">Avvalgi parolingizni piriting</label>
            <input
                    name="old_password"
                class="para black curve-border"
                type="password"
                    minlength="8"
                placeholder="Eski parol"
                required />
        </div>
        <div class="gr">
            <label class="black">Yangi parol kiriting</label>
            <input
                    name="password1"
                class="para black new_password curve-border"
                type="password"
                placeholder="Yangi parol"
                minlength="8"
                required />
        </div>
        <div class="gr">
            <label class="black">Parolni takrorlang</label>
            <input
                    name="password2"
                class="para black confirm_password curve-border"
                type="password"
                placeholder="Parolni Takrorlang"
                minlength="8"
                required />
        </div>

        <button class="curve-border btn black  " type="submit">Parolni o'zgartirish</button>
        <div class="additional">
            <a href="{% url 'password_reset' %}" class="blue"
                >Parol esdan chiqdimi?</a
            >
        </div>
    </form>
      </div>
{% endblock %}

templates/default_auth/reset_password.html
{% extends 'pages/profile.html' %}
{% load static %}
{% block title %}Parolni tiklash{% endblock %}
{% block main %}

<div
    style="
        height: 92lvh;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        gap: 30px;
    ">
    <h1 class="heading">Parolni tiklash</h1>
    <form method="post" class="form curve-border inset-shadow">
        {% csrf_token %}
        <div class="gr" style="flex-direction: column-reverse">
            <input
                name="phone"
                id="id_phone"
                class="para black phone_input curve-border"
                type="tel"
                placeholder="telefon raqam"
                pattern="\+998\s[0-9]{2}\s[0-9]{3}\s[0-9]{2}-[0-9]{2}"
                required />
            <label for="id_phone">Telefon raqam</label>
        </div>

        <button type="submit" class="btn">SMS yuborish</button>
        {{ form.errors }}
    </form>
</div>
{% endblock %}
<script src="/static/js/auth.js"></script>
<script>
    const phoneInput = document.querySelector(".phone_input");

    phoneInput.addEventListener("focus", function () {
        if (!phoneInput.value.startsWith("+998")) {
            phoneInput.value = "+998 ";
        }
    });

    phoneInput.addEventListener("input", function () {
        let input = phoneInput.value.replace(/\D/g, "");
        if (input.startsWith("998")) {
            input = input.substring(3);
        }

        let formattedNumber = "+998 ";
        if (input.length > 0) {
            formattedNumber += input.substring(0, 2);
        }
        if (input.length > 2) {
            formattedNumber += " " + input.substring(2, 5);
        }
        if (input.length > 5) {
            formattedNumber += " " + input.substring(5, 7);
        }
        if (input.length > 7) {
            formattedNumber += "-" + input.substring(7, 9);
        }

        phoneInput.value = formattedNumber;
    });

    phoneInput.addEventListener("keydown", function (event) {
        const position = phoneInput.selectionStart;
        if (position < 5 && event.key !== "Backspace") {
            event.preventDefault();
        }
    });

    phoneInput.addEventListener("blur", function () {
        if (phoneInput.value === "+998 ") {
            phoneInput.value = "";
        }
    });
</script>

templates/default_auth/reset_password_confirm.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Parolni tiklash{% endblock %}
{% block css %}{% static 'css/accounts/reset_password.css' %}{% endblock %}

{% block content %}
    
    
    
    
    
    <h2 class="heading">Yangi parolni o'rnating</h2>
    <form method="POST" class="form">
        {% csrf_token %}
         <div class="gr">
        <label for="password1">Yangi parol</label>
        <input id="password1" type="password" class="para black curve-border" name="new_password1">
         </div>
      <div class="gr">
            <label for="password2">Yangi parol (qayta)</label>
        <input id="password2" type="password" class="para black curve-border" name="new_password2">
      </div>
        <button class="btn curve-border black  " type="submit">Parolni o'zgartirish</button>
    </form>
{% endblock %}

templates/default_auth/reset_password_confirm_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        <div style="padding: 100px;" class="container curve-border ">
        <h1 class=" important-text">Parolingizni muvaffaqiyatli o'zgartirdingiz.</h1>
            <p>Yangi parol bilan saytga kirishingiz mumkin.</p>
            
        <a href="{% url 'login' %}" class="btn  white curve-border">Yangi parol bilan kirish</a>
            
        <a href="{% url 'home' %}" class="btn  white curve-border">Asosiy sahifaga qaytish</a>
    </div>

{% endblock  %}

templates/default_auth/reset_password_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        <div style="padding: 100px;" class="container curve-border ">
        <h1 class=" important-text">Parolni tiklash linki telefon raqamingizga yuborildi.</h1>
            
        <a href="{% url 'home' %}" class="btn  white curve-border">Asosiy sahifaga qaytish</a>
    </div>

{% endblock  %}